const GITHUB_AUTH_TOKEN = "ghp_ava5RQuQqsVmk7E7IRo40mgwssto3l42iBc"
const BOT_NUMBER = "94701242477"
const SESSION_ID = "PRABATH-MD~GThiCZDb#THPeobzeXtTlWoYURKLNeIMBT0_mO4ahJ20sCGalfVk"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
